# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slopometer',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/slopometer',
                'lib_path': 'slopometer'},
  'syms': {'slopometer.core': {'slopometer.core.foo': ('core.html#foo', 'slopometer/core.py')}}}
