"""Tells, findings, the rule registry, and what the meter cannot see

slopometer measures prose against the reference-prose rules in `aai_coding.write_docs`: 26 numbered tells, the named ways reference prose goes wrong. This module defines what every rule shares: the table of tells, the `Finding` record every detector returns, the registry that rules join at import time, and the registry of tells no deterministic rule can detect.

Docs: https://AnswerDotAI.github.io/slopometer/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['tells', 'KILL', 'SMELL', 'PRESSURE', 'rules', 'unscoreable', 'Finding', 'rule', 'find_decoration']

# %% ../nbs/00_core.ipynb #fa403df1
from fastcore.utils import *

# %% ../nbs/00_core.ipynb #5fecc627
tells = {
    1: 'splices',              2: 'contract by aside',       3: 'emphasis devices',
    4: 'elegant variation',    5: 'flourish over identifier', 6: 'consequence glue',
    7: 'hedging',              8: 'noting fillers',          9: 'restatement',
    10: 'justification rider', 11: 'decorative verbs',       12: 'audience misjudged',
    13: 'throat-clearing',     14: "today's-world opener",   15: 'announce-then-deliver',
    16: 'not-X-but-Y',         17: 'teaser pivot',           18: 'rhetorical questions',
    19: 'filler transitions',  20: 'forced symmetry',        21: 'appraisal preamble',
    22: 'artifact-as-agent',   23: 'recipient-as-subject',   24: 'decoration',
    25: 'over-structuring',    26: 'false depth'}

# %% ../nbs/00_core.ipynb #94d1c18f
KILL,SMELL,PRESSURE = 10,3,1

# %% ../nbs/00_core.ipynb #705a0d27
class Finding:
    def __init__(self,
        rule, # Name of the rule that fired
        tell, # `write_docs` tell number the rule detects
        start, # Character offset where the span starts, within the text the detector received
        end, # Character offset one past the span's end
        text, # The offending span itself
        weight, # The rule's tier, escalated where the rule escalates
        suggestion=None, # A mechanical replacement, when one exists
    ): store_attr()
    def __repr__(self):
        sug = f' -> {self.suggestion!r}' if self.suggestion else ''
        tl = '' if self.tell is None else f' (tell {self.tell}, {tells[self.tell]})'
        return f'[{self.weight}] {self.rule}{tl}: {self.text!r}{sug}'

# %% ../nbs/00_core.ipynb #50e848c5
rules = {}

def rule(
    name, # Rule name, unique within slopometer
    tell, # `write_docs` tell number the rule detects
    weight, # Tier the rule's findings carry
    level, # The unit the detector reads: 'phrase', 'sentence', 'para', or 'doc'
):
    "Register a detector, a function from its unit's text to the list of `Finding`s in it"
    def _f(f):
        f.tell,f.weight,f.level = tell,weight,level
        rules[name] = f
        return f
    return _f

# %% ../nbs/00_core.ipynb #d45bdd74
_ornament = re.compile(r'[\u2190-\u2bff\ufe0f\U0001f000-\U0001faff]+')
_arrows = {'→':'->', '⇒':'=>', '←':'<-', '↔':'<->'}

@rule('decoration', tell=24, weight=KILL, level='phrase')
def find_decoration(txt):
    "Flag emoji and ornamental unicode, suggesting ASCII for arrows"
    return [Finding('decoration', 24, m.start(), m.end(), m.group(), KILL, _arrows.get(m.group()))
        for m in _ornament.finditer(txt)]

# %% ../nbs/00_core.ipynb #1af3670a
unscoreable = {
    2: 'knowing which fact is the contract takes judgment',
    5: "telling a flourish from a real identifier takes the project's vocabulary",
    9: 'lead-sentence restatement defeats averaged sentence vectors, and only the heading echo is detectable (measured in the para notebook)',
    10: 'a justification rider reads like a stated consequence, and only the domain says which it is',
    11: 'verb texture beyond the banned-verb lexicon is a whiteboard judgment',
    12: 'matching prose to its audience takes the audience, and the coinage rule covers only the definable half',
    26: 'depth is judged against what the reader already knows',}
