"""Build the labeled corpus: weak positives from scored replies, mixed human negatives

Training the learned scorer needs labeled text, and no human has labeled any. This module builds the corpus by weak supervision: the rules pick confident slop from my own reply history, human-authored sources supply the clean side, and the ambiguous middle joins neither. The one human-labeled set, replies that drew a complaint in a session, is written separately and reserved for evaluation. Rows carry their source, so any experiment can slice, reweight, or hold out a source later.

Docs: https://AnswerDotAI.github.io/slopometer/corpus.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_corpus.ipynb.

# %% auto #0
__all__ = ['GH_REPOS', 'CL_SKIP', 'label_overlap', 'label_density', 'reply_final', 'mirror_replies', 'doc_paras', 'readme_paras',
           'user_requests', 'gh_readme_asof', 'gh_readme_paras', 'wiki_paras', 'wiki_pair', 'complaint_labels',
           'build_corpus']

# %% ../nbs/08_corpus.ipynb #a2a2e052
import base64, json, httpx
from collections import Counter
from datetime import datetime, timedelta
from fastcore.utils import *
from fastcore.xdg import xdg_state_home
from .core import *
from .segment import *
from .lexicon import *
from .syntax import *
from .para import *
from .score import *
from .features import *

# %% ../nbs/08_corpus.ipynb #91073b23
from .features import _conn

def label_overlap():
    "Words shared between the connective feature sets and any rule lexicon"
    lexs = set(banned) | set(hedges) | set(noting) | set(transitions) | set(wordy)
    return set().union(*_conn.values()) & lexs

def label_density(txt):
    "Density with findings on `label_overlap` words dropped: the label-side scorer"
    ov = label_overlap()
    fs = [f for f in run_rules(txt) if f.text.lower() not in ov]
    return round(100*sum(f.weight for f in fs)/max(prose_words(segment(txt)), 1), 1)

# %% ../nbs/08_corpus.ipynb #22cd8e39
_toolblock = re.compile(r'```json \{\.tool\}.*?```', re.S)

def reply_final(out):
    "The text after the last tool block: the final message the user read"
    return _toolblock.split(out)[-1].strip()

def _mirror_prompts(days, path_re):
    "Prompt messages from recent mirrored sessions, each with its mirror path"
    from llmsurgery.mirror import index
    from aidialog.dlgskill import find_msgs
    from rgapi.skill import fd
    root = index().root
    cutoff = datetime.now() - timedelta(days=days)
    for p in fd(root, ext='ipynb', path_re=path_re):
        if p.mtime <= cutoff: continue
        yield from ((p, m) for m in find_msgs(msg_type='prompt', context=0, dlg=str(root/p)))

def mirror_replies(
    days=21, # How far back to walk the mirror
    min_words=50, # Word floor per final
    path_re='-aai-ws', # Mirror filename filter: this machine's workspace projects
):
    "One (text, source, ref) row per qualifying reply final in recent mirrored sessions"
    rows = []
    for p, m in _mirror_prompts(days, path_re):
        txt = reply_final(m.out or '')
        if len(txt.split()) >= min_words: rows.append(dict(text=txt, source='reply', ref=f'{p}#{m.id}'))
    return rows


# %% ../nbs/08_corpus.ipynb #49194eeb
def doc_paras(txt, source, ref, min_words=50):
    "One row per prose paragraph of `min_words`+ words in markdown `txt`"
    return [dict(text=b.txt, source=source, ref=f'{ref}@{b.start}')
        for b in segment(txt) if b.kind=='prose' and len(b.txt.split()) >= min_words]

async def readme_paras(
    org='AnswerDotAI', # GitHub org to list
    before='2025-06-01', # Keep repos created before this date
    root='~/aai-ws', # Keep repos also checked out here
    exclude=('internal-web', 'answerdotai'), # Repos to drop by name
    min_words=50, # Word floor per paragraph
):
    "Rows from the READMEs of `org` repos created before `before` and checked out under `root`"
    from ghapi.skill import GhGql
    from rgapi.skill import ls
    gql = GhGql()
    names = [o['name'] async for o in gql.paged(gql.organization(login=org).repositories, 'name createdAt isFork')
        if o['createdAt'][:10] < before and not o['isFork']]
    names = sorted(set(names) & {p.rstrip('/') for p in ls(root, dirs=True, files=False)} - set(exclude))
    txts = await gql.batch(gql.repo(f'{org}/{n}').object(expression='HEAD:README.md')('... on Blob { text }') for n in names)
    return [r for n, t in zip(names, txts) if t for r in doc_paras(t['text'], 'readme', f'{org}/{n}', min_words)]

# %% ../nbs/08_corpus.ipynb #2b73beca
_notuser = ('Stop hook feedback', '<bash-', '<command-', 'system-reminder', '<local-command')

def user_requests(
    days=90, # How far back to walk the mirror
    min_words=50, # Word floor per prompt
    path_re='-aai-ws', # Mirror filename filter
):
    "One row per long typed user prompt in recent mirrored sessions"
    return [dict(text=m.content, source='request', ref=f'{p}#{m.id}')
        for p, m in _mirror_prompts(days, path_re)
        if len((m.content or '').split()) >= min_words and not any(t in m.content for t in _notuser)]

# %% ../nbs/08_corpus.ipynb #b6f6b68b
GH_REPOS = [  # chkstyle: ignore-node
    '3b1b/manim', 'BurntSushi/ripgrep', 'FFmpeg/FFmpeg', 'FiloSottile/mkcert', 'Genymobile/scrcpy',
    'NationalSecurityAgency/ghidra', 'Textualize/rich', 'alacritty/alacritty', 'angular/angular', 'ansible/ansible',
    'apache/superset', 'axios/axios', 'bitcoin/bitcoin', 'caddyserver/caddy', 'chartjs/Chart.js',
    'coder/code-server', 'd3/d3', 'denoland/deno', 'django/django', 'elastic/elasticsearch',
    'electron/electron', 'excalidraw/excalidraw', 'expressjs/express', 'facebook/docusaurus', 'fastapi/fastapi',
    'flutter/flutter', 'gin-gonic/gin', 'git/git', 'godotengine/godot', 'gohugoio/hugo',
    'golang/go', 'grafana/grafana', 'hakimel/reveal.js', 'home-assistant/core', 'huggingface/transformers',
    'jellyfin/jellyfin', 'jesseduffield/lazygit', 'jquery/jquery', 'junegunn/fzf', 'keras-team/keras',
    'kubernetes/kubernetes', 'laravel/laravel', 'laurent22/joplin', 'localstack/localstack', 'lodash/lodash',
    'meilisearch/meilisearch', 'mermaid-js/mermaid', 'minio/minio', 'moby/moby', 'mrdoob/three.js',
    'mui/material-ui', 'neovim/neovim', 'nestjs/nest', 'netdata/netdata', 'nodejs/node',
    'nuxt/nuxt', 'nvm-sh/nvm', 'obsproject/obs-studio', 'ocornut/imgui', 'ohmyzsh/ohmyzsh',
    'opencv/opencv', 'pallets/flask', 'pi-hole/pi-hole', 'prometheus/prometheus', 'protocolbuffers/protobuf',
    'puppeteer/puppeteer', 'python/cpython', 'pytorch/pytorch', 'rails/rails', 'rclone/rclone',
    'react/react', 'redis/redis', 'reduxjs/redux', 'rust-lang/rust', 'scikit-learn/scikit-learn',
    'scrapy/scrapy', 'sharkdp/bat', 'socketio/socket.io', 'spring-projects/spring-boot', 'starship/starship',
    'storybookjs/storybook', 'strapi/strapi', 'supabase/supabase', 'sveltejs/svelte', 'swiftlang/swift',
    'syncthing/syncthing', 'tailwindlabs/tailwindcss', 'tauri-apps/tauri', 'tensorflow/tensorflow', 'tesseract-ocr/tesseract',
    'tldr-pages/tldr', 'traefik/traefik', 'twbs/bootstrap', 'typst/typst', 'vercel/next.js',
    'vitejs/vite', 'vuejs/vue', 'webpack/webpack', 'yt-dlp/yt-dlp', 'ytdl-org/youtube-dl']

async def gh_readme_asof(api, owner, repo, date='2022-06-01'):
    "The text of `owner/repo`'s README as of `date`, or None when none exists"
    cs = await api.repos.list_commits(owner=owner, repo=repo, path='README.md', until=f'{date}T00:00:00Z', per_page=1)
    if not cs: return None
    from fasttransport.errors import APIError
    try: r = await api.repos.get_content(owner=owner, repo=repo, path='README.md', ref=cs[0].sha)
    except APIError as e:
        if e.status_code != 404: raise
        return None
    return base64.b64decode(r.content).decode()

async def gh_readme_paras(repos=GH_REPOS, date='2022-06-01', min_words=50):
    "Rows from the curated repos' READMEs, as each stood at `date`"
    from ghapi.skill import GhApi
    from fasttransport.errors import APIError
    api = GhApi()
    rows = []
    for rp in repos:
        try: txt = await gh_readme_asof(api, *rp.split('/'), date)
        except APIError as e:
            if not getattr(e, 'retryable', False): raise
            continue
        if txt: rows += doc_paras(txt, 'gh_readme', f'{rp}@{date}', min_words)
    return rows


# %% ../nbs/08_corpus.ipynb #9e49ecc7
def _wiki_get(lang, tries=2, **params):
    for i in range(tries):
        try:
            r = httpx.get(f'https://{lang}.wikipedia.org/w/api.php', follow_redirects=True, timeout=30,
                headers={'User-Agent': 'slopometer/0.1 (https://github.com/AnswerDotAI/slopometer)'},
                params=dict(action='query', prop='extracts', explaintext=1, exintro=1, format='json', **params))
            return r.json()['query']['pages'].values()
        except httpx.TimeoutException:
            if i == tries-1: raise

def wiki_paras(n=40, lang='en', min_words=50):
    "Rows from `n` random article intros in `lang` ('simple' for Simple English)"
    rows, seen = [], set()
    while len(seen) < n:
        for p in _wiki_get(lang, generator='random', grnnamespace=0, grnlimit=min(20, n-len(seen))):
            t = p.get('extract', '')
            if not t or p['title'] in seen: continue
            seen.add(p['title'])
            rows += doc_paras(t, f'wiki_{lang}', f'{lang}:{p["title"]}', min_words)
    return rows

def wiki_pair(title):
    "The intro of `title` from English and Simple English Wikipedia"
    return {lang: first(_wiki_get(lang, titles=title, redirects=1)).get('extract', '') for lang in ('en', 'simple')}

# %% ../nbs/08_corpus.ipynb #f2b906da
_complaint = re.compile(r"simple precise|plain english|too (long|verbose|wordy)|(can'?t|cannot|don'?t) follow|\brestate\b|\bshorter\b", re.I)

CL_SKIP = {'08a3c8f8', '114221e9', '153523c5', '185087ce', '2c42451b', '2cb78850', '440a8bbc',
    '6e8014b7', '7fc03936', '8f82f36b', 'a553ccb0', 'd0432f76', 'f0f5d6b3'}

def complaint_labels(
    days=90, # How far back to walk the mirror
    path_re='-aai-ws', # Mirror filename filter
):
    "One row per reply final that drew a `;` or a clarity complaint"
    rows, prev, prevp = [], None, None
    for p, m in _mirror_prompts(days, path_re):
        if prevp != p: prev = None
        c = (m.content or '').strip()
        short = len(c.split()) <= 30 and not any(t in c for t in _notuser) and not c.startswith('#')
        if prev and m.id not in CL_SKIP and (c == ';' or (len(c.split()) <= 3 and 'simplif' in c.lower()) or (short and _complaint.search(c))):
            rows.append(dict(text=prev, source='complaint', ref=f'{p}#{m.id}', prompt=c[:100]))
        txt = reply_final(m.out or '')
        prev, prevp = (txt if len(txt.split()) >= 10 else None), p
    return rows

# %% ../nbs/08_corpus.ipynb #6d20d4d0
from fastcore.parallel import parallel

def _densities(rows):
    "Attach `label_density` to each row, threaded"
    for r, d in zip(rows, parallel(label_density, [r['text'] for r in rows], n_workers=8, threadpool=True)): r['dens'] = d
    return rows

async def build_corpus(
    pos_cut=50, # Label density at or above which a reply counts as slop
    neg_cut=30, # Label density at or below which a human paragraph counts as clean
    wiki_n=150, # Random articles per wiki
    out=None, # Output directory; default under XDG state
):
    "Fetch every source, apply the density cuts, and write `corpus.jsonl` and `eval.jsonl`"
    negs = _densities(await readme_paras() + user_requests() + await gh_readme_paras()
        + wiki_paras(wiki_n) + wiki_paras(wiki_n, lang='simple'))
    pos = _densities(mirror_replies())
    rows = [dict(**r, label='slop') for r in pos if r['dens'] >= pos_cut]
    rows += [dict(**r, label='clean') for r in negs if r['dens'] <= neg_cut]
    d = Path(out) if out else xdg_state_home()/'slopometer'
    d.mkdir(parents=True, exist_ok=True)
    (d/'corpus.jsonl').write_text('\n'.join(json.dumps(r) for r in rows))
    (d/'eval.jsonl').write_text('\n'.join(json.dumps(r) for r in complaint_labels()))
    return Counter((r['source'], r['label']) for r in rows)
