"""Continuous measurements for learned scoring

The rules keep only what crosses a bar, and a learned scorer wants the bar removed. This module measures prose as continuous numbers: every rule's findings as a rate, the sentence and paragraph distributions the thresholds truncate, the parts-of-speech profile, specifics density, referential load, and burstiness. Three of these measures failed earlier as threshold rules, and the para and score notebooks record why. As features they need no threshold, because a learned combiner such as a random forest weighs them against labeled examples. The score stays rule-based and explainable. The feature vector exists for calibration experiments, and anything the experiments validate can graduate into a rule.

Docs: https://AnswerDotAI.github.io/slopometer/features.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_features.ipynb.

# %% auto #0
__all__ = ['burstiness', 'flattest_window', 'features']

# %% ../nbs/07_features.ipynb #e0f7d103
import statistics
from collections import Counter
from fastcore.utils import *
from .core import *
from .segment import *
from .lexicon import *
from .syntax import *
from .para import *
from .score import run_rules

# %% ../nbs/07_features.ipynb #bc8d7df9
def burstiness(xs):
    "Goh-Barabasi B over `xs`: -1 uniform, 0 random, positive bursty"
    if len(xs) < 2: return 0.0
    m, s = statistics.mean(xs), statistics.stdev(xs)
    return 0.0 if m + s == 0 else round((s - m) / (s + m), 3)

def flattest_window(
    xs, # Sentence lengths, in document order
    k=5, # Window size in sentences
):
    "`(start, spread)` of the length-`k` run with the lowest variation, for localizing monotone stretches"
    if len(xs) <= k: return 0, round(statistics.stdev(xs), 2) if len(xs) > 1 else 0.0
    spans = [(i, round(statistics.stdev(xs[i:i+k]), 2)) for i in range(len(xs) - k + 1)]
    return min(spans, key=lambda t: t[1])

# %% ../nbs/07_features.ipynb #b422bd19
_conn = dict(add={'also', 'furthermore', 'moreover', 'additionally'}, causal={'because', 'therefore', 'thus', 'hence'},
    advers={'but', 'however', 'although', 'though', 'yet'})

def features(txt):
    "Continuous measurements of markdown `txt`, one flat dict"
    blocks = segment(txt)
    docs = parse_blocks(blocks)
    prose = [d for d in docs if d is not None]
    sents = [s for d in prose for s in d.sents]
    toks = [t for d in prose for t in d]
    nw = max(sum(1 for t in toks if t.is_alpha), 1)
    res = dict(words=nw, sents=len(sents), headings=n_headings(blocks))
    agg = Counter()
    for f in run_rules(txt): agg[f.rule] += f.weight
    res |= {f'r_{k}': round(100*v/nw, 2) for k, v in agg.items()}
    res['density'] = round(100*sum(agg.values())/nw, 1)
    slens = [sum(1 for t in s if not t.is_punct) for s in sents]
    if len(slens) > 1:
        res |= dict(slen_mean=round(statistics.mean(slens), 1), slen_max=max(slens), slen_burst=burstiness(slens))
        starts = [next((t.lemma_.lower() for t in s if t.is_alpha), '') for s in sents]
        res['start_div'] = round(len(set(starts))/len(starts), 2)
    plens = [sum(1 for _ in d.sents) for d in prose]
    if plens: res |= dict(psents_mean=round(statistics.mean(plens), 1), psents_max=max(plens))
    pos = Counter(t.pos_ for t in toks)
    res |= dict(adv=round(100*pos['ADV']/nw, 1), adj=round(100*pos['ADJ']/nw, 1),
        noun_verb=round(pos['NOUN']/max(pos['VERB'], 1), 2),
        cop=round(sum(1 for s in sents if s.root.lemma_ == 'be')/max(len(sents), 1), 2))
    ncode = sum(len(re.findall(r'X{2,}', scrub(b.txt))) for b in blocks)
    res['specifics'] = round(100*(pos['NUM'] + pos['PROPN'] + ncode)/nw, 1)
    res['pron_subj'] = round(sum(1 for s in sents if any(t.dep_ in ('nsubj', 'nsubjpass') and t.pos_ == 'PRON'
        and t.head.dep_ == 'ROOT' for t in s))/max(len(sents), 1), 2)
    seen, ndef, ncold = set(), 0, 0
    for d in prose:
        for t in d:
            if t.pos_ not in ('NOUN', 'PROPN') or len(set(t.lower_)) == 1: continue
            lem = t.lemma_.lower()
            kids = [c.lower_ for c in t.children]
            if 'the' in kids and 'same' not in kids:
                ndef += 1
                if lem not in seen: ncold += 1
            seen.add(lem)
    res |= dict(defs=ndef, cold=round(ncold/max(ndef, 1), 2))
    res |= {f'conn_{k}': round(100*sum(1 for t in toks if t.lemma_.lower() in v)/nw, 2) for k, v in _conn.items()}
    return res
