"""Word and phrase rules: banned vocabulary, hedges, fillers, and splices

The phrase-level rules: banned vocabulary with plain replacements, hedge phrases, noting fillers, filler transitions, splice punctuation, consequence glue, and markdown emphasis. Each is a regex over a block's scrubbed text, needs no linguistic analysis, and runs in microseconds.

Docs: https://AnswerDotAI.github.io/slopometer/lexicon.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_lexicon.ipynb.

# %% auto #0
__all__ = ['banned', 'find_banned', 'hedges', 'noting', 'transitions', 'find_hedges', 'find_noting', 'find_transitions', 'wordy',
           'find_wordy', 'lex_rule', 'find_splice', 'find_conseq', 'find_emphasis']

# %% ../nbs/02_lexicon.ipynb #23bc602c
from fastcore.utils import *
from .core import *
from .segment import *


# %% ../nbs/02_lexicon.ipynb #449d550b
def lex_rule(
    name, # Rule name, as in `core.rule`
    tell, # `write_docs` tell number
    weight, # Tier the findings carry
    lex, # Vocabulary: word or phrase -> plain replacement, or None where deletion is the fix
    suffix=False, # Also match inflected forms of each key?
):
    "Build and register a phrase rule that scans for `lex` entries case-insensitively"
    tail = r'\w*' if suffix else ''
    pat = re.compile(r'\b(' + '|'.join(re.escape(k) for k in sorted(lex, key=len, reverse=True)) + r')' + tail + r'\b', re.I)
    def _f(txt): return [Finding(name, tell, m.start(), m.end(), m.group(), weight, lex.get(m.group(1).lower())) for m in pat.finditer(txt)]
    _f.__name__,_f.__doc__ = f'find_{name}',f'Scan for the {name} vocabulary'
    return rule(name, tell=tell, weight=weight, level='phrase')(_f)

# %% ../nbs/02_lexicon.ipynb #e9411861
banned = {'utilize': 'use', 'utilise': 'use', 'leverage': 'use', 'facilitate': 'help', 'robust': 'strong',
    'comprehensive': 'complete', 'seamless': 'smooth', 'enhance': 'improve', 'streamline': None,
    'empower': None, 'foster': 'encourage', 'pivotal': None, 'a testament to': None, 'realm': None,
    'landscape': None, 'delve': None, 'myriad': None, 'plethora': None, 'paradigm': None,
    'synergy': None, 'holistic': None, 'catalyze': None, 'catalyse': None, 'juxtapose': None,
    'tapestry': None, 'embark': None, 'endeavor': None, 'endeavour': None, 'encompass': None,
    'multifaceted': None, 'elucidate': 'explain', 'nuanced': None, 'liaise': None, 'overarching': None,
    'countless': 'many', 'incentivize': None, 'incentivise': None, 'game-changer': None,
    'cutting-edge': None, 'best-in-class': None, 'deliver results': None,
    # adopted from the GOV.UK words-to-avoid list (OGL v3) and no-cliches (MIT); evidence below
    'initiate': 'start', 'tackle': 'solve', 'a clean slate': None, 'in a nutshell': None}

find_banned = lex_rule('banned', tell=None, weight=KILL, lex=banned, suffix=True)

# %% ../nbs/02_lexicon.ipynb #ef8d80e3
hedges = {'potentially': None, 'in some cases': None, 'should generally': None, 'may or may not': None,
    'one might argue': None, 'it could be argued': None, 'arguably': None, 'more or less': None,
    # weasel words adopted from write-good's weasel-words (MIT); evidence below
    'very': None, 'quite': None, 'extremely': None, 'fairly': None, 'exceedingly': None, 'remarkably': None,
    'surprisingly': None, 'interestingly': None, 'clearly': None, 'completely': None, 'largely': None,
    'mostly': None, 'relatively': None, 'usually': None, 'significantly': None, 'substantially': None,
    'huge': None, 'tiny': None, 'vast': None, 'few': None, 'several': None, 'excellent': None}
noting = {'note that': None, "it's worth noting": None, 'it is worth noting': None, 'worth mentioning': None,
    'importantly': None, 'notably': None, 'keep in mind': None, 'bear in mind': None, 'it should be noted': None}
transitions = {'furthermore': 'and', 'moreover': 'and', 'additionally': 'also', 'in conclusion': None,
    'when it comes to': None, 'in the realm of': None}

find_hedges = lex_rule('hedges', tell=7, weight=SMELL, lex=hedges)
find_noting = lex_rule('noting', tell=8, weight=SMELL, lex=noting)
find_transitions = lex_rule('transitions', tell=19, weight=SMELL, lex=transitions)

# %% ../nbs/02_lexicon.ipynb #79549961
_splice = re.compile(r'—|(?<=\w) -- (?=\w)|(?<=\w); (?=\w)|(?<=\w) - (?=\w)')
_conseq = re.compile(r', so\b')

@rule('splice', tell=1, weight=KILL, level='phrase')
def find_splice(txt):
    "Em dashes, two-hyphen dashes, semicolon joins, and spaced-hyphen joins"
    return [Finding('splice', 1, m.start(), m.end(), m.group(), KILL) for m in _splice.finditer(txt)]

@rule('conseq', tell=6, weight=SMELL, level='phrase')
def find_conseq(txt):
    "The ', so' consequence join"
    return [Finding('conseq', 6, m.start(), m.end(), m.group(), SMELL) for m in _conseq.finditer(txt)]

# %% ../nbs/02_lexicon.ipynb #8daaf936
_emph = re.compile(r'\*\*[^*\n]+\*\*|(?<![\w*])\*[^*\s][^*\n]*\*(?![\w*])|(?<![\w_])__[^_\n]+__(?![\w_])')

@rule('emphasis', tell=3, weight=SMELL, level='phrase')
def find_emphasis(txt):
    "Bold and italic markers in running prose"
    return [Finding('emphasis', 3, m.start(), m.end(), m.group(), SMELL) for m in _emph.finditer(txt)]

# %% ../nbs/02_lexicon.ipynb #cdb0967f
wordy = {'all of': 'all', 'additional': 'more', 'a number of': 'some', 'along the lines of': 'like',
    'already existing': 'existing', 'adjacent to': 'next to', 'anticipate': 'expect',
    'in order to': 'to', 'going forward': 'from now on'}

find_wordy = lex_rule('wordy', tell=None, weight=SMELL, lex=wordy)
