"""Score prose with Pangram's AI detector, as an alternative to the rules

`pangram_text` and `pangram_path` send prose to [Pangram](https://www.pangram.com)'s AI-detection API instead of running the rules. They read the same Markdown as `score_text` and `score_path`. They return a `Result` with the same addresses, JSON fields and `min_words` cutoff. `slopometer --pangram` runs `pangram_path` from the command line.

Pangram scores text in windows, which can run to hundreds of words. Each finding is one window. Its weight is the window's score multiplied by 10. A window that Pangram rates fully AI-written weighs 10, the same as a kill-tier rule finding. The density is the mean window score, weighted by word count, on a scale from 0 (human) to 100 (AI). Under `--pangram`, `--threshold` compares against this scale.

Each request sends the text to Pangram's servers and costs about $0.05 per 100 words. The functions read the API key from `PANGRAM_API_KEY`.

Docs: https://AnswerDotAI.github.io/slopometer/pangram.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05a_pangram.ipynb.

# %% auto #0
__all__ = ['PANGRAM_URL', 'PangramFinding', 'PangramResult', 'pangram_text', 'pangram_path', 'pangram_paths']

# %% ../nbs/05a_pangram.ipynb #50ef2286
import time, httpx2
from bisect import bisect_right
from fastcore.utils import *
from .core import *
from .segment import *
from .score import Result, _score_file, _doc_paths

# %% ../nbs/05a_pangram.ipynb #a265951c
def _pangram_input(blocks):
    "Text to send to Pangram for `blocks`, and each block's offset in it"
    offs, n = [], 0
    for b in blocks:
        offs.append(n)
        n += len(b.txt) + 1
    return '\n'.join(b.txt for b in blocks), offs

# %% ../nbs/05a_pangram.ipynb #a1383847
PANGRAM_URL = 'https://text.external-api.pangram.com'

def _predict(
    text, # Text to classify
    timeout=120, # Seconds to wait for the task to finish
):
    "Pangram's response for `text`, from a task posted to its API and polled until done"
    with httpx2.Client(base_url=PANGRAM_URL, headers={'x-api-key': os.environ['PANGRAM_API_KEY']}) as cli:
        tid = cli.post('/task', json=dict(text=text, model='default')).raise_for_status().json()['task_id']
        for _ in range(timeout*2):
            res = cli.get(f'/task/{tid}').raise_for_status().json()
            if res['stage'] == 'STAGE_SUCCESS': return res
            if res['stage'] == 'STAGE_FAILED': raise RuntimeError(f'Pangram task {tid} failed')
            time.sleep(0.5)
    raise TimeoutError(f'Pangram task {tid} did not finish in {timeout} seconds')

# %% ../nbs/05a_pangram.ipynb #ddbc675b
class PangramFinding(Finding):
    def __init__(self,
        start, # Character offset where the window starts
        end, # Character offset one past the window's end
        text, # The window's text
        score, # Pangram's `ai_assistance_score`, from 0 (human) to 1 (AI)
        label, # Pangram's label, such as 'AI-Generated' or 'Human Written'
        confidence, # 'High', 'Medium', or 'Low'
        words, # Words in the window
    ):
        super().__init__('pangram', None, start, end, text, round(10*score))
        store_attr('score,label,confidence,words')
    def __repr__(self):
        ex = self.text if len(self.text) <= 80 else self.text[:77]+'...'
        return f'[{self.weight}] pangram {self.score:.2f} {self.label}, {self.confidence} confidence, {self.words} words: {ex!r}'

# %% ../nbs/05a_pangram.ipynb #392e91e1
class PangramResult(Result):
    def __init__(self,
        txt, # The scored document
        findings, # `PangramFinding`s, worst first
        words, # Word count across all scored blocks
        payload=None, # Pangram's response; None when no request was sent
        min_words=150, # Minimum scored words; 0 disables the cutoff
    ):
        super().__init__(txt, findings, words, min_words=min_words)
        self.payload = payload
    def _header(self): return f'pangram score {self.density} on {self.words} prose words, worst {self.worst}'

# %% ../nbs/05a_pangram.ipynb #acd5edf6
@patch(as_prop=True)
def density(self:PangramResult):
    "Mean window score, weighted by word count and scaled to 0-100"
    if self.too_short: return None
    n = sum(f.words for f in self.findings)
    return round(100*sum(f.score*f.words for f in self.findings)/max(n, 1), 1)

# %% ../nbs/05a_pangram.ipynb #098e727a
def _pangram_result(txt, payload, min_words=150):
    "`PangramResult` for markdown `txt`, with the windows in Pangram's `payload` mapped back to document offsets"
    blocks = segment(txt)
    sent, offs = _pangram_input(blocks)
    if payload['text'] != sent: raise ValueError('Pangram scored different text from the text sent, and its window offsets cannot be mapped')
    def doc_off(i):
        k = bisect_right(offs, i) - 1
        return blocks[k].start + min(i-offs[k], len(blocks[k].txt))
    fs = [PangramFinding(doc_off(w['start_index']), doc_off(w['end_index']-1)+1, w['text'], w['ai_assistance_score'],
        w['label'], w['confidence'], w['word_count']) for w in payload['windows']]
    return PangramResult(txt, sorted(fs, key=lambda f: (-f.score, f.start)), scored_words(blocks), payload, min_words)

# %% ../nbs/05a_pangram.ipynb #24c81a92
def pangram_text(txt, min_words=150):
    "Score markdown `txt` with Pangram, sending no request below `min_words` scored words"
    if min_words < 0: raise ValueError('min_words must be non-negative')
    blocks = segment(txt)
    words = scored_words(blocks)
    if not words or words < min_words: return PangramResult(txt, [], words, min_words=min_words)
    return _pangram_result(txt, _predict(_pangram_input(blocks)[0]), min_words)

# %% ../nbs/05a_pangram.ipynb #db5d53f7
def pangram_path(p, min_words=150):
    "Score a Markdown file, an `.ipynb` file's Markdown cells, or a `.py` file's module docstring with Pangram, with exhash addresses"
    return _score_file(p, pangram_text, min_words)

def pangram_paths(paths, n_workers=8, min_words=150):
    "Score files and directories with Pangram in parallel threads, one `PangramResult` per file"
    return parallel(pangram_path, _doc_paths(paths), n_workers=n_workers, threadpool=True, min_words=min_words)
