"""Paragraph rules: restatement, elegant variation, forced symmetry, and coinage

The rules that read a whole paragraph: restatement, elegant variation, forced symmetry, and coinage. The first two need a way to measure whether two different word sequences say the same thing, and word vectors provide it. The paragraph is the largest unit any of these rules analyzes, and coinage, which counts across paragraphs, does so with arithmetic alone.

Docs: https://AnswerDotAI.github.io/slopometer/para.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_para.ipynb.

# %% auto #0
__all__ = ['find_heading_echo', 'parse_blocks', 'find_variation', 'find_triad', 'find_bullet_mold', 'find_para_cap',
           'find_coinage']

# %% ../nbs/04_para.ipynb #adcc3c9f
from collections import Counter
from fastcore.utils import *
from .core import *
from .segment import *
from .syntax import *

# %% ../nbs/04_para.ipynb #625319b7
def _content(toks): return {t.lemma_.lower() for t in toks if t.is_alpha and not t.is_stop}

@rule('heading_echo', tell=9, weight=SMELL, level='doc')
def find_heading_echo(blocks, docs):
    "A section's first sentence repeating its heading's words"
    res = []
    for b,nxt,d in zip(blocks, blocks[1:], docs[1:]):
        if b.kind != 'heading' or nxt.kind != 'prose' or d is None: continue
        hw = _content(get_nlp()(scrub(b.txt.lstrip('# '))))
        if not hw: continue
        s1 = list(d.sents)[0]
        lead = first((t.lemma_.lower() for t in s1 if t.is_alpha and not t.is_stop), None)
        if lead in hw and hw <= _content(s1): res.append(Finding('heading_echo', 9, nxt.start, nxt.start+len(s1.text), s1.text, SMELL))
    return res

# %% ../nbs/04_para.ipynb #a2dbc1cf
def parse_blocks(blocks):
    "The spaCy `Doc` for each prose block, aligned with `blocks`, None elsewhere"
    prose = [b for b in blocks if b.kind=='prose']
    parsed = iter(get_nlp().pipe([scrub(b.txt) for b in prose]))
    return [next(parsed) if b.kind=='prose' else None for b in blocks]

# %% ../nbs/04_para.ipynb #16ad69f8
_variant_pairs = [{'folder', 'directory'}, {'method', 'function'}, {'parameter', 'argument'}, {'error', 'exception'}, {'docstring', 'documentation'}]

@rule('variation', tell=4, weight=SMELL, level='para')
def find_variation(doc):
    "Two names for one concept within a paragraph, by curated pair or shared stem"
    seen,res,done = {},[],set()
    for t in doc:
        if t.pos_ not in ('NOUN', 'PROPN') or not t.is_alpha or len(set(t.lower_)) == 1: continue
        lem = t.lemma_.lower()
        for prev in seen:
            if prev == lem: continue
            pair = any(prev in s and lem in s for s in _variant_pairs)
            stem = (len(min(lem, prev, key=len)) >= 4 and (lem in prev or prev in lem)
                and not doc.vocab[lem].is_oov and not doc.vocab[prev].is_oov)
            if (pair or stem) and frozenset((prev, lem)) not in done:
                done.add(frozenset((prev, lem)))
                res.append(Finding('variation', 4, t.idx, t.idx+len(t.text), f'{seen[prev].text} ... {t.text}', SMELL))
                break
        seen[lem] = t
    return res

# %% ../nbs/04_para.ipynb #5ce63501
@rule('triad', tell=20, weight=SMELL, level='para')
def find_triad(doc):
    "Three or more coordinated nouns sharing one modifier lemma"
    res = []
    for t in doc:
        if t.pos_ != 'NOUN': continue
        group = [t] + [c for c in t.conjuncts if c.pos_ == 'NOUN']
        if len(group) < 3 or any(g.i < t.i for g in group): continue
        mods = [{m.lemma_ for m in g.children if m.dep_ == 'amod'} for g in group]
        shared = set.intersection(*mods) if all(mods) else set()
        if shared:
            span = doc.text[group[0].idx:group[-1].idx+len(group[-1].text)]
            res.append(Finding('triad', 20, group[0].idx, group[-1].idx+len(group[-1].text), span, SMELL))
    return res

@rule('bullet_mold', tell=20, weight=SMELL, level='doc')
def find_bullet_mold(blocks, docs):
    "Three or more consecutive list items opening with the same word"
    res,run = [],[]
    def word(b): return re.sub(r'^\s*(?:[-*+]|\d+[.)]) +', '', b.txt).split(' ')[0].lower() if b.txt else ''
    for b in list(blocks) + [None]:
        if b is not None and b.kind == 'item':
            run.append(b)
            continue
        if len(run) >= 3 and len({word(x) for x in run}) == 1:
            res.append(Finding('bullet_mold', 20, run[0].start, run[-1].start+len(run[-1].txt), '\n'.join(x.txt for x in run), SMELL))
        run = []
    return res

# %% ../nbs/04_para.ipynb #ddc5a702
@rule('para_cap', tell=None, weight=PRESSURE, level='para')
def find_para_cap(doc):
    "Paragraphs past 150 words, escalating per extra 25"
    n = sum(1 for t in doc if t.is_alpha)
    if n <= 150: return []
    return [Finding('para_cap', None, 0, len(doc.text), f'{n}-word paragraph', PRESSURE*((n-150)//25 + 1))]


# %% ../nbs/04_para.ipynb #236fd005
@rule('coinage', tell=12, weight=SMELL, level='doc')
def find_coinage(blocks, docs):
    "A recurring out-of-vocabulary term outside backticks"
    cnt,firsts = Counter(),{}
    for b,d in zip(blocks, docs):
        if d is None: continue
        for t in d:
            if not t.is_alpha or len(t.text) < 4 or not t.text.islower() or not t.is_oov: continue
            cnt[t.text] += 1
            if t.text not in firsts: firsts[t.text] = (b.start+t.idx, b.start+t.idx+len(t.text))
    return [Finding('coinage', 12, *firsts[w], w, SMELL) for w,c in cnt.items() if c >= 2]
