"""Run every rule, weigh the findings, and report worst first

The meter assembled: one pass that segments a document, runs every registered rule at its level, rebases every finding onto document offsets, and reduces the findings to two numbers. Density is weighted findings per 100 prose words, and the max is the single worst finding. A clean document scores near zero on both. One kill-on-sight finding pushes the max to 10 alone, which is the tiers doing their job.

Docs: https://AnswerDotAI.github.io/slopometer/score.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_score.ipynb.

# %% auto #0
__all__ = ['find_overstructure', 'run_rules', 'Result', 'score_text', 'score_path', 'score_many']

# %% ../nbs/05_score.ipynb #68d2aa09
from fastcore.utils import *
from fastcore.tools import lnhash_at
from .core import *
from .segment import *
from .lexicon import *
from .syntax import *
from .para import *

# %% ../nbs/05_score.ipynb #d2f5895b
@rule('overstructure', tell=25, weight=SMELL, level='doc')
def find_overstructure(blocks, docs):
    "More headings than the prose beneath them justifies"
    nh,nw = n_headings(blocks), prose_words(blocks)
    if nh < 2 or nw/nh >= 40: return []
    hs = [b for b in blocks if b.kind == 'heading']
    return [Finding('overstructure', 25, hs[0].start, hs[0].start+len(hs[0].txt),
        f'{nh} headings on {nw} words of prose', SMELL)]

# %% ../nbs/05_score.ipynb #3d4515d6
def _rebase(fs, off):
    for f in fs:
        f.start += off
        f.end += off
    return fs

def run_rules(txt):
    "Every registered rule's findings for markdown `txt`, rebased to document offsets"
    blocks = segment(txt)
    docs = parse_blocks(blocks)
    out = []
    for b,d in zip(blocks, docs):
        sc = scrub(b.txt)
        for r in rules.values():
            if r.level == 'phrase': out += _rebase(r(sc), b.start)
            elif d is None: continue
            elif r.level == 'sentence':
                for s in d.sents: out += _rebase(r(s), b.start+s.start_char)
            elif r.level == 'para': out += _rebase(r(d), b.start)
    for r in rules.values():
        if r.level == 'doc': out += r(blocks, docs)
    return sorted(out, key=lambda f: (-f.weight, f.start))


# %% ../nbs/05_score.ipynb #829de200
class Result:
    def __init__(self,
        txt, # The scored document
        findings, # `Finding`s, worst first
        words, # Prose word count
        path=None, # Source file, when scoring a file
    ):
        store_attr()
        for f in findings:
            if len(f.text) == f.end-f.start and '\n' not in txt[f.start:f.end]: f.text = txt[f.start:f.end]
    @property
    def total(self): return sum(f.weight for f in self.findings)
    @property
    def density(self): return round(100*self.total/max(self.words, 1), 1)
    @property
    def worst(self): return max((f.weight for f in self.findings), default=0)
    def _addr(self, f):
        ln = self.txt[:f.start].count('\n')+1
        return lnhash_at(self.txt, ln) if self.path else f'{ln}:'
    def __repr__(self):
        hdr = f'density {self.density} (weight {self.total} on {self.words} prose words), worst {self.worst}'
        if self.path: hdr = f'{self.path}: {hdr}'
        return '\n'.join([hdr] + [f'{self._addr(f)} {f!r}' for f in self.findings])

def score_text(txt):
    "Score markdown `txt`, returning a `Result`"
    return Result(txt, run_rules(txt), prose_words(segment(txt)))

def score_path(p):
    "Score the file at `p` (expands `~`); report rows carry exhash addresses"
    p = Path(p).expanduser()
    txt = p.read_text()
    return Result(txt, run_rules(txt), prose_words(segment(txt)), path=p)


# %% ../nbs/05_score.ipynb #0e3b855b
def score_many(txts, n_workers=8):
    "Score texts in parallel threads, returning a `Result` per text"
    return parallel(score_text, txts, n_workers=n_workers, threadpool=True)
