"""Run every rule, weigh the findings, and report worst first

The meter assembled: one pass that segments a document, runs every registered rule at its level, rebases every finding onto document offsets, and reduces the findings to two numbers. Density is weighted findings per 100 prose words, and the max is the single worst finding. A clean document scores near zero on both. One kill-on-sight finding pushes the max to 10 alone, which is the tiers doing their job.

Docs: https://AnswerDotAI.github.io/slopometer/score.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_score.ipynb.

# %% auto #0
__all__ = ['find_overstructure', 'run_rules', 'Result', 'score_text', 'score_path', 'score_many']

# %% ../nbs/05_score.ipynb #68d2aa09
from fastcore.utils import *
from fastcore.tools import lnhash_at
from .core import *
from .segment import *
from .lexicon import *
from .syntax import *
from .para import *

# %% ../nbs/05_score.ipynb #d2f5895b
@rule('overstructure', tell=25, weight=SMELL, level='doc')
def find_overstructure(blocks, docs):
    "More headings than the prose beneath them justifies"
    nh,nw = n_headings(blocks), prose_words(blocks)
    if nh < 2 or nw/nh >= 40: return []
    hs = [b for b in blocks if b.kind == 'heading']
    return [Finding('overstructure', 25, hs[0].start, hs[0].start+len(hs[0].txt),
        f'{nh} headings on {nw} words of prose', SMELL)]

# %% ../nbs/05_score.ipynb #3d4515d6
def _rebase(fs, off):
    for f in fs:
        f.start += off
        f.end += off
    return fs

def run_rules(txt):
    "Every registered rule's findings for markdown `txt`, rebased to document offsets"
    blocks = segment(txt)
    docs = parse_blocks(blocks)
    out = []
    for b,d in zip(blocks, docs):
        sc = scrub(b.txt)
        for r in rules.values():
            if r.level == 'phrase': out += _rebase(r(sc), b.start)
            elif d is None: continue
            elif r.level == 'sentence':
                for s in d.sents: out += _rebase(r(s), b.start+s.start_char)
            elif r.level == 'para': out += _rebase(r(d), b.start)
    for r in rules.values():
        if r.level == 'doc': out += r(blocks, docs)
    return sorted(out, key=lambda f: (-f.weight, f.start))


# %% ../nbs/05_score.ipynb #829de200
class Result:
    def __init__(self,
        txt, # The scored document
        findings, # `Finding`s, worst first
        words, # Word count across all scored blocks
        path=None, # Source file, when scoring a file
        min_words=150, # Minimum scored words; 0 disables the cutoff
    ):
        store_attr()
        for f in findings:
            if len(f.text) == f.end-f.start and '\n' not in txt[f.start:f.end]: f.text = txt[f.start:f.end]
    @property
    def too_short(self): return self.words < self.min_words
    @property
    def total(self): return None if self.too_short else sum(f.weight for f in self.findings)
    @property
    def density(self): return None if self.too_short else round(100*self.total/max(self.words, 1), 1)
    @property
    def worst(self): return None if self.too_short else max((f.weight for f in self.findings), default=0)
    def _addr(self, f):
        ln = self.txt[:f.start].count('\n')+1
        return lnhash_at(self.txt, ln) if self.path else f'{ln}:'
    def __repr__(self):
        if self.too_short: hdr = f'too short to meter ({self.words} scored words; minimum {self.min_words})'
        else: hdr = f'density {self.density} (weight {self.total} on {self.words} prose words), worst {self.worst}'
        if self.path: hdr = f'{self.path}: {hdr}'
        return '\n'.join([hdr] + [f'{self._addr(f)} {f!r}' for f in self.findings])

def score_text(txt, min_words=150):
    "Score markdown `txt`, skipping rule evaluation below `min_words` scored words"
    if min_words < 0: raise ValueError('min_words must be non-negative')
    words = scored_words(segment(txt))
    return Result(txt, run_rules(txt) if words >= min_words else [], words, min_words=min_words)

def score_path(p, min_words=150):
    "Score the file at `p` (expands `~`); report rows carry exhash addresses"
    p = Path(p).expanduser()
    res = score_text(p.read_text(), min_words=min_words)
    res.path = p
    return res


# %% ../nbs/05_score.ipynb #0e3b855b
def score_many(txts, n_workers=8, min_words=150):
    "Score texts in parallel threads, applying `min_words` to each text"
    return parallel(score_text, txts, n_workers=n_workers, threadpool=True, min_words=min_words)
