"""Markdown becomes typed blocks that keep their file positions

Rules read prose, but slopometer's input is markdown: READMEs, docstrings rendered from notebooks, PR text, chat responses. Segmentation turns a markdown document into typed blocks (heading, list item, prose paragraph) that remember where they came from, discards fenced code entirely, and blanks inline code so that lexical rules never fire on identifiers. Every downstream stage depends on the position bookkeeping here: a finding is only useful if it can point back at the exact file offset it came from.

Docs: https://AnswerDotAI.github.io/slopometer/segment.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_segment.ipynb.

# %% auto #0
__all__ = ['Block', 'segment', 'scrub', 'n_headings', 'prose_words']

# %% ../nbs/01_segment.ipynb #694196b8
from fastcore.utils import *
import mdhtml
from .core import *

# %% ../nbs/01_segment.ipynb #8e3a315e
class Block:
    def __init__(self,
        kind, # 'heading', 'item', or 'prose'
        txt, # The block's text, sliced verbatim from the document after iframe blanking
        start, # Character offset of the block in the document
    ): store_attr()
    def __repr__(self): return f'<{self.kind} @{self.start}: {self.txt[:48]!r}>'

_iframe = re.compile(r'<iframe\b.*?</iframe\s*>', re.S | re.I)
_item = re.compile(r'^\s*(?:[-*+]|\d+[.)]) ')
_KINDS = dict(paragraph='prose', heading='heading')

def segment(doc):
    "Split markdown `doc` into typed `Block`s that keep their character offsets"
    doc = _iframe.sub(lambda m: re.sub(r'[^\n]', ' ', m.group()), doc)
    lines = doc.split('\n')
    offs, n = [], 0
    for l in lines:
        offs.append(n)
        n += len(l) + 1
    out = []
    for b in mdhtml.blocks(doc):
        seg = lines[b['start']:b['end']]
        if b['type'] == 'list':
            out += [Block('item', l, offs[b['start']+i]) for i,l in enumerate(seg) if _item.match(l)]
        elif b['type'] in _KINDS:
            txt = '\n'.join(seg).strip('\n')
            if txt.strip(): out.append(Block(_KINDS[b['type']], txt, offs[b['start']]))
    return L(out)

# %% ../nbs/01_segment.ipynb #6c25fbfe
_icode = re.compile(r'`[^`\n]+`')
_ltarget = re.compile(r'\]\([^)\n]+\)')

def scrub(txt):
    "Replace inline code with X-fill and link targets with spaces, keeping every offset unchanged"
    txt = _icode.sub(lambda m: 'X'*len(m.group()), txt)
    return _ltarget.sub(lambda m: ' '*len(m.group()), txt)


# %% ../nbs/01_segment.ipynb #6052473a
def n_headings(blocks): return sum(1 for b in blocks if b.kind=='heading')
def prose_words(blocks): return sum(len(b.txt.split()) for b in blocks if b.kind=='prose')
