"""Markdown becomes typed blocks that keep their file positions

Rules read prose, but slopometer's input is markdown: READMEs, docstrings rendered from notebooks, PR text, chat responses. Segmentation turns a markdown document into typed blocks (heading, list item, prose paragraph) that remember where they came from, discards fenced code entirely, and blanks inline code so that lexical rules never fire on identifiers. Every downstream stage depends on the position bookkeeping here: a finding is only useful if it can point back at the exact file offset it came from.

Docs: https://AnswerDotAI.github.io/slopometer/segment.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_segment.ipynb.

# %% auto #0
__all__ = ['Block', 'segment', 'scrub', 'n_headings', 'prose_words', 'scored_words']

# %% ../nbs/01_segment.ipynb #694196b8
from fastcore.utils import *
import mdhtml
from .core import *

# %% ../nbs/01_segment.ipynb #8e3a315e
class Block:
    def __init__(self,
        kind, # 'heading', 'item', or 'prose'
        txt, # The block's text, sliced verbatim from the document after iframe blanking
        start, # Character offset of the block in the document
    ): store_attr()
    def __repr__(self): return f'<{self.kind} @{self.start}: {self.txt[:48]!r}>'

_iframe = re.compile(r'<iframe\b.*?</iframe\s*>', re.S | re.I)
_item = re.compile(r'^\s*(?:[-*+]|\d+[.)]) ')

def segment(doc):
    "Split markdown `doc` into typed `Block`s that keep their character offsets"
    doc = _iframe.sub(lambda m: re.sub(r'[^\n]', ' ', m.group()), doc)
    lines = doc.split('\n')
    offs, n = [], 0
    for l in lines:
        offs.append(n)
        n += len(l) + 1
    out, quotes = [], []
    for b in mdhtml.blocks(doc, nested=True):
        quotes = [q for q in quotes if q['depth'] < b['depth'] and b['start'] < q['end']]
        if b['type'] == 'block_quote': quotes.append(b)
        if quotes or b['type'] not in ('paragraph', 'heading'): continue
        raw = '\n'.join(lines[b['start']:b['end']])
        txt = raw.strip()
        if not txt: continue
        kind = 'heading' if b['type'] == 'heading' else 'item' if _item.match(txt) else 'prose'
        out.append(Block(kind, txt, offs[b['start']] + len(raw) - len(raw.lstrip())))
    return L(out)

# %% ../nbs/01_segment.ipynb #6c25fbfe
def scrub(txt):
    "Keep `txt`'s plain text, fill its inline code with X, and turn all other markup into spaces, keeping every offset unchanged"
    out = [c if c == '\n' else ' ' for c in txt]
    for n in mdhtml.inlines(txt):
        a,b = n['start'], n['end']
        if n['type'] == 'text': out[a:b] = txt[a:b]
        elif n['type'] == 'code': out[a:b] = 'X'*(b-a)
    return ''.join(out)

# %% ../nbs/01_segment.ipynb #6052473a
def n_headings(blocks): return sum(1 for b in blocks if b.kind=='heading')
def prose_words(blocks): return sum(len(b.txt.split()) for b in blocks if b.kind=='prose')

def scored_words(blocks):
    "Whitespace-separated words in every scored block, excluding heading and list markers"
    return sum(len(re.sub(r'^\s*(?:#{1,6}|[-*+]|\d+[.)])\s+', '', b.txt).split()) for b in blocks)
