"""The spaCy rules: sentences, clauses, passives, and the patterns anchored to them

The rules that need to know what a sentence is and how its words relate: sentence length, clause count, passive voice, part-of-speech-dependent vocabulary, noun clusters, nominalizations, agent defocusing, and the slop patterns that anchor to sentence starts. [spaCy](https://spacy.io) provides the linguistic analysis, and this module also owns getting spaCy's model onto the machine.

Docs: https://AnswerDotAI.github.io/slopometer/syntax.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_syntax.ipynb.

# %% auto #0
__all__ = ['MODEL', 'MODEL_PKG', 'MODEL_URL', 'find_throat', 'find_todays', 'find_announce', 'find_notxbuty', 'find_teaser',
           'find_appraisal', 'model_path', 'get_nlp', 'find_sent_len', 'find_clauses', 'find_passive',
           'find_verb_banned', 'find_intensifiers', 'find_noun_cluster', 'find_nominalization', 'find_artifact_agent',
           'find_recipient_subject', 'sent_rule', 'find_rhetorical']

# %% ../nbs/03_syntax.ipynb #e2b9a004
import spacy, zipfile, shutil, importlib
from fastcore.utils import *
from fastcore.net import urlsave
from fastcore.xdg import xdg_cache_home
from .core import *
from .segment import *

# %% ../nbs/03_syntax.ipynb #4e72a817
MODEL = 'en_core_web_md-3.8.0'
MODEL_PKG = MODEL.rsplit('-', 1)[0]
MODEL_URL = f'https://github.com/explosion/spacy-models/releases/download/{MODEL}/{MODEL}-py3-none-any.whl'

def model_path():
    "Path of the model data directory: the installed package if present, else the cache, downloading on first call"
    try: return Path(importlib.import_module(MODEL_PKG).__file__).parent/MODEL
    except ImportError: pass
    dest = xdg_cache_home()/'slopometer'
    p = dest/MODEL
    if p.exists(): return p
    print(f'slopometer: downloading {MODEL} (~40MB, once per machine) to {p}')
    dest.mkdir(parents=True, exist_ok=True)
    whl = urlsave(MODEL_URL, dest/f'{MODEL}.whl')
    with zipfile.ZipFile(whl) as z:
        pfx = f'{MODEL_PKG}/{MODEL}/'
        for n in z.namelist():
            if n.startswith(pfx): z.extract(n, dest/'tmp')
    shutil.move(dest/'tmp'/MODEL_PKG/MODEL, p)
    shutil.rmtree(dest/'tmp')
    Path(whl).unlink()
    return p

_nlp = None
def get_nlp():
    "The loaded pipeline, one per process"
    global _nlp
    if _nlp is None: _nlp = spacy.load(model_path())
    return _nlp

# %% ../nbs/03_syntax.ipynb #d8078a42
@rule('sent_len', tell=1, weight=PRESSURE, level='sentence')
def find_sent_len(sent):
    "Sentences past 25 words, escalating one weight point per extra word"
    n = sum(1 for t in sent if not t.is_punct)
    if n <= 25: return []
    return [Finding('sent_len', 1, 0, len(sent.text), sent.text, PRESSURE*(n-25))]

_clausy = {'advcl', 'ccomp'}

def _own_subj(t): return any(c.dep_ in ('nsubj', 'nsubjpass', 'expl') for c in t.children)

@rule('clauses', tell=1, weight=PRESSURE, level='sentence')
def find_clauses(sent):
    "Sentences stacking four or more idea-bearing clauses, escalating per extra clause"
    n = 1 + sum(1 for t in sent if t.pos_ in ('VERB', 'AUX')
        and (t.dep_ in _clausy or (t.dep_ == 'conj' and _own_subj(t))))
    if n < 4: return []
    return [Finding('clauses', 1, 0, len(sent.text), sent.text, PRESSURE*(n-3))]

# %% ../nbs/03_syntax.ipynb #9431332d
@rule('passive', tell=None, weight=SMELL, level='sentence')
def find_passive(sent):
    "Passive constructions, weighted higher when no agent survives"
    res = []
    for t in sent:
        if t.dep_ != 'nsubjpass': continue
        v = t.head
        agented = any(c.dep_ == 'agent' for c in v.children)
        span = sent.text[t.idx-sent.start_char:v.idx-sent.start_char+len(v.text)]
        res.append(Finding('passive', None, t.idx-sent.start_char, v.idx-sent.start_char+len(v.text), span, PRESSURE if agented else SMELL))
    return res

# %% ../nbs/03_syntax.ipynb #6db9f87a
_verb_banned = dict(impact='affect', land=None, shape=None, ride=None)
_intens = {'simply', 'merely', 'effortlessly'}

def _tok_find(name, tell, weight, sent, pred, lex=None):
    "Findings for tokens of `sent` passing `pred`, with optional suggestions from `lex`"
    return [Finding(name, tell, t.idx-sent.start_char, t.idx-sent.start_char+len(t.text), t.text, weight,
        lex.get(t.lemma_) if lex else None) for t in sent if pred(t)]

@rule('verb_banned', tell=None, weight=KILL, level='sentence')
def find_verb_banned(sent):
    "Words banned as verbs, caught by lemma and POS"
    return _tok_find('verb_banned', None, KILL, sent, lambda t: t.pos_ == 'VERB' and t.lemma_ in _verb_banned
        and not (t.i > 0 and t.nbor(-1).text == '-'), _verb_banned)

@rule('intensifiers', tell=3, weight=SMELL, level='sentence')
def find_intensifiers(sent):
    "Ease-claiming adverbs"
    return _tok_find('intensifiers', 3, SMELL, sent, lambda t: t.pos_ == 'ADV' and t.lemma_ in _intens)

# %% ../nbs/03_syntax.ipynb #0442a84f
_light = {'make', 'take', 'perform', 'conduct', 'do', 'carry'}
_denoun = dict(decision='decide', assessment='assess', improvement='improve', comparison='compare',
    configuration='configure', modification='modify', evaluation='evaluate', determination='determine',
    implementation='implement', investigation='investigate', selection='select', validation='validate')

@rule('noun_cluster', tell=None, weight=PRESSURE, level='sentence')
def find_noun_cluster(sent):
    "Runs of three or more nouns, escalating per extra noun"
    res,run = [],[]
    for t in list(sent) + [None]:
        if t is not None and t.pos_ in ('NOUN', 'PROPN'):
            run.append(t)
            continue
        n = sum(x.pos_ == 'NOUN' for x in run)
        if n >= 3:
            span = sent.text[run[0].idx-sent.start_char:run[-1].idx-sent.start_char+len(run[-1].text)]
            res.append(Finding('noun_cluster', None, run[0].idx-sent.start_char, run[-1].idx-sent.start_char+len(run[-1].text), span, PRESSURE*(n-2)))
        run = []
    return res

@rule('nominalization', tell=None, weight=SMELL, level='sentence')
def find_nominalization(sent):
    "Light verbs carrying a nominalized object"
    res = []
    for t in sent:
        if t.pos_ == 'VERB' and t.lemma_ in _light:
            for c in t.children:
                if c.dep_ == 'dobj' and c.lemma_ in _denoun:
                    span = sent.text[t.idx-sent.start_char:c.idx-sent.start_char+len(c.text)]
                    res.append(Finding('nominalization', None, t.idx-sent.start_char, c.idx-sent.start_char+len(c.text), span, SMELL, _denoun[c.lemma_]))
    return res

# %% ../nbs/03_syntax.ipynb #7b3c63b5
_artifacts = {'pr', 'commit', 'change', 'patch', 'release', 'update', 'design', 'proposal', 'document', 'doc', 'readme', 'section', 'paragraph', 'refactor'}
_credit_verbs = {'introduce', 'enable', 'allow', 'let', 'add', 'improve', 'fix', 'ensure', 'provide', 'bring', 'unlock'}

@rule('artifact_agent', tell=22, weight=SMELL, level='sentence')
def find_artifact_agent(sent):
    "Authored artifacts credited with their author's deed"
    res = []
    for t in sent:
        if t.dep_ == 'nsubj' and t.lemma_.lower() in _artifacts and t.head.lemma_ in _credit_verbs:
            span = sent.text[t.idx-sent.start_char:t.head.idx-sent.start_char+len(t.head.text)]
            res.append(Finding('artifact_agent', 22, t.idx-sent.start_char, t.head.idx-sent.start_char+len(t.head.text), span, SMELL))
    return res

@rule('recipient_subject', tell=23, weight=SMELL, level='sentence')
def find_recipient_subject(sent):
    "Beneficiaries promoted to subject with gain/receive, or get with a via phrase"
    res = []
    for t in sent:
        if t.pos_ != 'VERB' or t.lemma_ not in ('gain', 'receive', 'get'): continue
        if not any(c.dep_ == 'nsubj' for c in t.children): continue
        demoted = any(c.lemma_ in ('via', 'through') for c in t.subtree if c.pos_ == 'ADP')
        if t.lemma_ == 'get' and not demoted: continue
        res.append(Finding('recipient_subject', 23, t.idx-sent.start_char, t.idx-sent.start_char+len(t.text), t.text, SMELL))
    return res

# %% ../nbs/03_syntax.ipynb #69415f9a
def sent_rule(
    name, # Rule name, as in `core.rule`
    tell, # `write_docs` tell number
    weight, # Tier the findings carry
    pats, # Phrase list; each becomes a case-insensitive regex alternative
    anchored=False, # Match only at the sentence start?
):
    "Build and register a sentence rule that scans `pats` in the sentence text"
    pat = re.compile(('^' if anchored else '') + '(' + '|'.join(pats) + ')', re.I)
    def _f(sent): return [Finding(name, tell, m.start(), m.end(), m.group(), weight) for m in pat.finditer(sent.text)]
    _f.__name__,_f.__doc__ = f'find_{name}',f'Scan for {name} phrases'
    return rule(name, tell=tell, weight=weight, level='sentence')(_f)

find_throat = sent_rule('throat_clearing', 13, SMELL, [r"this (?:section|document|readme|page|guide|module|doc|notebook) (?:describes|covers|explains|documents|provides|outlines|introduces)", r'the purpose of this'], anchored=True)
find_todays = sent_rule('todays_world', 14, SMELL, [r"in today's"], anchored=True)
find_announce = sent_rule('announce', 15, SMELL, [r"(?:the (?:fix|answer|solution|key|result|takeaway|core \w+)|here's the thing|bottom line): "], anchored=True)
find_notxbuty = sent_rule('notxbuty', 16, KILL, [r"\bis(?:n't| not) (?:just|merely|simply|only) (?:a|an|the|about)\b", r"\baren't (?:just|merely|simply|only)\b", r"\bit's not about\b", r"\bnot (?:just|merely) about\b"])
find_teaser = sent_rule('teaser', 17, SMELL, [r"here's where it gets", r'\bthe real story\b', r'\bgets (?:really )?interesting\b', r'\bthe main event\b'])
find_appraisal = sent_rule('appraisal', 21, SMELL, [r'\bworth being precise\b', r"\bthe key (?:point|insight|thing) is\b", r"\bwhat's interesting is\b", r'\bcrucially\b', r'\bthe important thing is\b'])

@rule('rhetorical', tell=18, weight=SMELL, level='sentence')
def find_rhetorical(sent):
    "Sentences that ask the reader a question"
    t = sent.text.rstrip()
    if not t.endswith('?'): return []
    return [Finding('rhetorical', 18, 0, len(t), t, SMELL)]
