"""The spaCy rules: sentences, clauses, passives, and the patterns anchored to them

This module uses [spaCy](https://spacy.io) to detect long sentences, stacked clauses, sentences with three or more punctuation-separated sections, passives, and part-of-speech-dependent vocabulary. It also checks noun clusters, nominalizations, actor placement, and phrases whose meaning depends on their position in a sentence. `get_nlp` downloads and loads the spaCy model.

Docs: https://AnswerDotAI.github.io/slopometer/syntax.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_syntax.ipynb.

# %% auto #0
__all__ = ['MODEL', 'MODEL_PKG', 'MODEL_URL', 'find_throat', 'find_todays', 'find_announce', 'find_notxbuty', 'find_teaser',
           'find_appraisal', 'model_path', 'get_nlp', 'find_sent_len', 'find_clauses', 'find_semi_splice',
           'find_sections', 'find_and_splice', 'find_passive', 'find_verb_banned', 'find_intensifiers',
           'find_noun_cluster', 'find_nominalization', 'find_artifact_agent', 'find_recipient_subject',
           'find_inert_act', 'find_inert_mind', 'sent_rule', 'find_rhetorical']

# %% ../nbs/03_syntax.ipynb #e2b9a004
import spacy, zipfile, shutil, importlib
from fastcore.utils import *
from fastcore.net import urlsave
from fastcore.xdg import xdg_cache_home
from .core import *
from .segment import *

# %% ../nbs/03_syntax.ipynb #4e72a817
MODEL = 'en_core_web_md-3.8.0'
MODEL_PKG = MODEL.rsplit('-', 1)[0]
MODEL_URL = f'https://github.com/explosion/spacy-models/releases/download/{MODEL}/{MODEL}-py3-none-any.whl'

def model_path():
    "Path of the model data directory: the installed package if present, else the cache, downloading on first call"
    try: return Path(importlib.import_module(MODEL_PKG).__file__).parent/MODEL
    except ImportError: pass
    dest = xdg_cache_home()/'slopometer'
    p = dest/MODEL
    if p.exists(): return p
    print(f'slopometer: downloading {MODEL} (~40MB, once per machine) to {p}')
    dest.mkdir(parents=True, exist_ok=True)
    whl = urlsave(MODEL_URL, dest/f'{MODEL}.whl')
    with zipfile.ZipFile(whl) as z:
        pfx = f'{MODEL_PKG}/{MODEL}/'
        for n in z.namelist():
            if n.startswith(pfx): z.extract(n, dest/'tmp')
    shutil.move(dest/'tmp'/MODEL_PKG/MODEL, p)
    shutil.rmtree(dest/'tmp')
    Path(whl).unlink()
    return p

_nlp = None
def get_nlp():
    "The loaded pipeline, one per process"
    global _nlp
    if _nlp is None: _nlp = spacy.load(model_path())
    return _nlp

# %% ../nbs/03_syntax.ipynb #d8078a42
_clausy = {'advcl', 'ccomp'}

def _own_subj(t): return any(c.dep_ in ('nsubj', 'nsubjpass', 'expl') for c in t.children)

def _n_clauses(sent):
    "How many idea-bearing clauses `sent` stacks"
    return 1 + sum(1 for t in sent if t.pos_ in ('VERB', 'AUX')
        and (t.dep_ in _clausy or (t.dep_ == 'conj' and _own_subj(t))))

@rule('sent_len', tell=1, weight=PRESSURE, level='sentence')
def find_sent_len(sent):
    "Multi-clause sentences past 25 words, escalating one weight point per extra word"
    n = sum(1 for t in sent if not t.is_punct)
    if n <= 25 or _n_clauses(sent) < 2: return []
    return [Finding('sent_len', 1, 0, len(sent.text), sent.text, PRESSURE*(n-25))]

@rule('clauses', tell=1, weight=PRESSURE, level='sentence')
def find_clauses(sent):
    "Sentences stacking four or more idea-bearing clauses, escalating per extra clause"
    n = _n_clauses(sent)
    if n < 4: return []
    return [Finding('clauses', 1, 0, len(sent.text), sent.text, PRESSURE*(n-3))]


# %% ../nbs/03_syntax.ipynb #1245fd6f
def _clausal(toks):
    "Do `toks` contain a finite clause: a subject attached to a verb?"
    return any(t.dep_.startswith('nsubj') and t.head.pos_ in ('VERB', 'AUX') for t in toks)

@rule('semi_splice', tell=1, weight=4, level='sentence')
def find_semi_splice(sent):
    "Semicolons joining two independent clauses; serial semicolons and citations pass"
    res, depth = [], 0
    for t in sent:
        if t.text == '(': depth += 1
        elif t.text == ')': depth = max(0, depth-1)
        elif t.text == ';' and not depth:
            if _clausal([x for x in sent if x.i < t.i]) and _clausal([x for x in sent if x.i > t.i]):
                o = t.idx - sent.start_char
                res.append(Finding('semi_splice', 1, o, o+1, ';', 4))
    return res

# %% ../nbs/03_syntax.ipynb #01e48875
_breaks = {',', ';', ':', '—', '–'}

def _is_break(t):
    "Does punctuation `t` end a section, counting a spaced hyphen as a dash?"
    if t.text in ('-', '--'): return bool(t.whitespace_) and t.i > 0 and bool(t.nbor(-1).whitespace_)
    return t.text in _breaks

def _verbless(toks): return not any(t.pos_ in ('VERB', 'AUX') for t in toks)

def _subject_last(seg):
    "Does `seg` open with a coordinator whose item spaCy parsed as the sentence's subject, as in 'and prompts work'?"
    return len(seg) > 1 and seg[0].dep_ == 'cc' and any(t.dep_.startswith('nsubj') and t.left_edge.i == seg[1].i for t in seg)

def _list_commas(toks, brks, parts):
    "Indexes into `brks` of commas between list items, given the `parts` of the sentence between breaks"
    segs = parts[1:]
    fronted = brks and _verbless(parts[0]) and not _verbless(toks[brks[0]:])
    res, j = set(), 0
    while j < len(brks):
        e = j
        while e < len(brks) and toks[brks[e]].text == ',' and not _clausal(segs[e]): e += 1
        subj = j == 0 and e < len(brks) and toks[brks[e]].text == ',' and _subject_last(segs[e]) and all(map(_verbless, parts[:e+1]))
        if j == 0 and fronted and not subj:
            j = 1
            continue
        run = segs[j:e+subj]
        if subj or any(t.dep_ == 'cc' for s in run for t in s) or len(run) > 1: res.update(range(j, e+subj))
        j = max(e+subj, j+1)
    return res

def _n_sections(sent):
    "How many sections punctuation splits `sent` into, with each list item kept whole"
    toks = list(sent[:-1] if sent[-1].is_punct else sent)
    brks, parens, hidden, depth = [], [], set(), 0
    for k,t in enumerate(toks):
        if depth or t.text == '(': hidden.add(k)
        if t.text == ')': depth = max(0, depth-1)
        elif not depth and t.text == '(': parens.append(k)
        elif not depth and _is_break(t): brks.append(k)
        if t.text == '(': depth += 1
    bounds = [-1] + brks + [len(toks)]
    parts = [[toks[i] for i in range(a+1, b) if i not in hidden] for a,b in zip(bounds, bounds[1:])]
    lists, n = _list_commas(toks, brks, parts), 1
    for j,k in enumerate(brks):
        if toks[k].text == ';': n += _clausal(toks[:k]) and _clausal(toks[k+1:])
        elif j not in lists: n += 1
    for k in parens:
        j = sum(b < k for b in brks)
        n += not ({j-1, j} & lists)
    return n

@rule('sections', tell=1, weight=PRESSURE, level='sentence')
def find_sections(sent):
    "Sentences that punctuation splits into three or more sections, escalating per extra section"
    n = _n_sections(sent)
    if n < 3: return []
    return [Finding('sections', 1, 0, len(sent.text), sent.text, PRESSURE*(n-2))]

# %% ../nbs/03_syntax.ipynb #24cb1828
@rule('and_splice', tell=1, weight=SMELL, level='sentence')
def find_and_splice(sent):
    "', and' joining a clause that has its own subject"
    res = []
    for t in sent[:-1]:
        a = t.nbor()
        if t.text != ',' or a.lower_ != 'and': continue
        end = next((x.i for x in sent.doc[a.i+1:sent.end] if _is_break(x)), sent.end)
        if not _clausal(sent.doc[a.i+1:end]): continue
        s,e = t.idx-sent.start_char, a.idx+len(a.text)-sent.start_char
        res.append(Finding('and_splice', 1, s, e, sent.text[s:e], SMELL))
    return res

# %% ../nbs/03_syntax.ipynb #9431332d
@rule('passive', tell=None, weight=0, level='sentence')
def find_passive(sent):
    "Passive constructions, listed without adding to the score"
    res = []
    for t in sent:
        if t.dep_ != 'nsubjpass': continue
        v = t.head
        s,e = t.idx-sent.start_char, v.idx-sent.start_char+len(v.text)
        res.append(Finding('passive', None, s, e, sent.text[s:e], 0))
    return res

# %% ../nbs/03_syntax.ipynb #6db9f87a
_verb_banned = dict(impact='affect', land=None, shape=None, ride=None)
_intens = {'simply', 'merely', 'effortlessly'}

def _tok_find(name, tell, weight, sent, pred, lex=None):
    "Findings for tokens of `sent` passing `pred`, with optional suggestions from `lex`"
    return [Finding(name, tell, t.idx-sent.start_char, t.idx-sent.start_char+len(t.text), t.text, weight,
        lex.get(t.lemma_) if lex else None) for t in sent if pred(t)]

@rule('verb_banned', tell=None, weight=KILL, level='sentence')
def find_verb_banned(sent):
    "Words banned as verbs, caught by lemma and POS"
    return _tok_find('verb_banned', None, KILL, sent, lambda t: t.pos_ == 'VERB' and t.lemma_ in _verb_banned
        and not (t.i > 0 and t.nbor(-1).text == '-'), _verb_banned)

@rule('intensifiers', tell=3, weight=SMELL, level='sentence')
def find_intensifiers(sent):
    "Ease-claiming adverbs"
    return _tok_find('intensifiers', 3, SMELL, sent, lambda t: t.pos_ == 'ADV' and t.lemma_ in _intens)

# %% ../nbs/03_syntax.ipynb #0442a84f
_light = {'make', 'take', 'perform', 'conduct', 'do', 'carry'}
_denoun = dict(decision='decide', assessment='assess', improvement='improve', comparison='compare',
    configuration='configure', modification='modify', evaluation='evaluate', determination='determine',
    implementation='implement', investigation='investigate', selection='select', validation='validate')

@rule('noun_cluster', tell=None, weight=PRESSURE, level='sentence')
def find_noun_cluster(sent):
    "Runs of three or more nouns, escalating per extra noun"
    res,run = [],[]
    for t in list(sent) + [None]:
        if t is not None and t.pos_ in ('NOUN', 'PROPN'):
            run.append(t)
            continue
        n = sum(x.pos_ == 'NOUN' for x in run)
        if n >= 3:
            span = sent.text[run[0].idx-sent.start_char:run[-1].idx-sent.start_char+len(run[-1].text)]
            res.append(Finding('noun_cluster', None, run[0].idx-sent.start_char, run[-1].idx-sent.start_char+len(run[-1].text), span, PRESSURE*(n-2)))
        run = []
    return res

@rule('nominalization', tell=None, weight=SMELL, level='sentence')
def find_nominalization(sent):
    "Light verbs carrying a nominalized object"
    res = []
    for t in sent:
        if t.pos_ == 'VERB' and t.lemma_ in _light:
            for c in t.children:
                if c.dep_ == 'dobj' and c.lemma_ in _denoun:
                    span = sent.text[t.idx-sent.start_char:c.idx-sent.start_char+len(c.text)]
                    res.append(Finding('nominalization', None, t.idx-sent.start_char, c.idx-sent.start_char+len(c.text), span, SMELL, _denoun[c.lemma_]))
    return res

# %% ../nbs/03_syntax.ipynb #7b3c63b5
_artifacts = {'pr', 'commit', 'change', 'patch', 'release', 'update', 'design', 'proposal', 'document', 'doc', 'readme', 'section', 'paragraph', 'refactor'}
_credit_verbs = {'introduce', 'enable', 'allow', 'let', 'add', 'improve', 'fix', 'ensure', 'provide', 'bring', 'unlock'}

@rule('artifact_agent', tell=22, weight=SMELL, level='sentence')
def find_artifact_agent(sent):
    "Authored artifacts credited with their author's deed"
    res = []
    for t in sent:
        if t.dep_ == 'nsubj' and t.lemma_.lower() in _artifacts and t.head.lemma_ in _credit_verbs:
            span = sent.text[t.idx-sent.start_char:t.head.idx-sent.start_char+len(t.head.text)]
            res.append(Finding('artifact_agent', 22, t.idx-sent.start_char, t.head.idx-sent.start_char+len(t.head.text), span, SMELL))
    return res

@rule('recipient_subject', tell=23, weight=SMELL, level='sentence')
def find_recipient_subject(sent):
    "Beneficiaries promoted to subject with gain/receive, or get with a via phrase"
    res = []
    for t in sent:
        if t.pos_ != 'VERB' or t.lemma_ not in ('gain', 'receive', 'get'): continue
        if not any(c.dep_ == 'nsubj' for c in t.children): continue
        demoted = any(c.lemma_ in ('via', 'through') for c in t.subtree if c.pos_ == 'ADP')
        if t.lemma_ == 'get' and not demoted: continue
        res.append(Finding('recipient_subject', 23, t.idx-sent.start_char, t.idx-sent.start_char+len(t.text), t.text, SMELL))
    return res

# %% ../nbs/03_syntax.ipynb #493c9d5c
_act_verbs = {  # chkstyle: ignore-node
    'accomplish', 'achieve', 'add', 'affix', 'arrange', 'assemble', 'assign', 'attach', 'bind', 'bolt', 'brand',
    'bring', 'build', 'carry', 'clamp', 'coin', 'construct', 'decorate', 'defend', 'deliver', 'detach',
    'disassemble', 'dismantle', 'distribute', 'download', 'drive', 'emboss', 'ensure', 'exert', 'fabricate',
    'fasten', 'feed', 'form', 'furnish', 'gather', 'generate', 'give', 'glue', 'grab', 'guard', 'hang', 'hook',
    'imprint', 'insert', 'inspect', 'invoke', 'keep', 'label', 'land', 'latch', 'leave', 'lock', 'make',
    'manipulate', 'mark', 'mint', 'modify', 'mount', 'name', 'offer', 'organize', 'pin', 'plug', 'print', 'procure',
    'produce', 'protect', 'pull', 'push', 'reassemble', 'record', 'release', 'remove', 'render', 'retain', 'ride',
    'separate', 'serve', 'shape', 'snap', 'stamp', 'stencil', 'stick', 'supply', 'survive', 'tie', 'wire', 'write'}
_mind_verbs = {  # chkstyle: ignore-node
    'abandon', 'accuse', 'acknowledge', 'admit', 'advise', 'aim', 'anticipate', 'appreciate', 'argue', 'assume',
    'attempt', 'believe', 'bother', 'care', 'choose', 'complain', 'comprehend', 'concede', 'consider', 'contend',
    'convince', 'criticize', 'decide', 'demand', 'deny', 'deserve', 'desire', 'disagree', 'doubt', 'earn',
    'emphasize', 'encourage', 'endeavour', 'expect', 'feel', 'forbid', 'forget', 'forgive', 'guess', 'hear', 'hope',
    'ignore', 'imagine', 'insist', 'intend', 'know', 'learn', 'like', 'listen', 'love', 'mind', 'miss', 'opt',
    'owe', 'own', 'pledge', 'praise', 'prefer', 'presume', 'pretend', 'promise', 'realize', 'reason', 'recognize',
    'recommend', 'refuse', 'reject', 'remember', 'remind', 'respect', 'seek', 'select', 'sense', 'speak', 'strive',
    'suppose', 'think', 'trust', 'try', 'understand', 'undertake', 'want', 'wish', 'wonder', 'worry'}
_people = {  # chkstyle: ignore-node
    'accountant', 'administrator', 'advisor', 'agent', 'architect', 'assistant', 'associate', 'author', 'blogger',
    'broker', 'buyer', 'caller', 'coach', 'coder', 'colleague', 'company', 'consultant', 'consumer', 'contractor',
    'contributor', 'coordinator', 'critic', 'customer', 'department', 'deputy', 'developer', 'director', 'editor',
    'electrician', 'employee', 'engineer', 'essayist', 'executive', 'filmmaker', 'folks', 'graduate', 'historian',
    'human', 'individual', 'intern', 'journalist', 'lecturer', 'listener', 'maintainer', 'manager', 'mechanic',
    'musician', 'novelist', 'officer', 'owner', 'people', 'person', 'playwright', 'poet', 'professor', 'programmer',
    'proprietor', 'provider', 'publisher', 'reader', 'reporter', 'reviewer', 'scientist', 'screenwriter',
    'secretary', 'somebody', 'someone', 'songwriter', 'squad', 'staff', 'storyteller', 'supervisor', 'team',
    'teammate', 'technician', 'trainee', 'user', 'vendor', 'viewer', 'writer'}
_runners = {  # chkstyle: ignore-node
    'actuator', 'algorithm', 'analyzer', 'app', 'applet', 'application', 'assembler', 'backend', 'bot', 'browser',
    'builder', 'call', 'callback', 'cell', 'checker', 'classifier', 'cli', 'client', 'command', 'compiler',
    'compressor', 'constructor', 'controller', 'converter', 'crawler', 'daemon', 'database', 'debugger',
    'decorator', 'detector', 'device', 'dispatcher', 'driver', 'engine', 'exporter', 'extension', 'firewall',
    'formatter', 'framework', 'frontend', 'function', 'gateway', 'generator', 'getter', 'handler', 'harness',
    'helper', 'hook', 'host', 'importer', 'instance', 'interpreter', 'inverter', 'iterator', 'kernel', 'library',
    'linter', 'loader', 'loop', 'magic', 'mapper', 'meter', 'method', 'microprocessor', 'mirror', 'model', 'modem',
    'module', 'operation', 'parser', 'partial', 'plugin', 'preprocessor', 'process', 'program', 'proxy', 'renderer',
    'router', 'runner', 'scanner', 'scheduler', 'scorer', 'script', 'search', 'selector', 'sensor', 'server',
    'service', 'shell', 'snippet', 'step', 'subroutine', 'subsystem', 'summarizer', 'system', 'terminal', 'test',
    'tester', 'thread', 'timer', 'tokenizer', 'tool', 'translator', 'transmitter', 'utility', 'widget', 'worker',
    'wrapper'}

# %% ../nbs/03_syntax.ipynb #3460be31
_actors = _people | _runners

def _inert_subj(sent, verbs, name, tell, weight):
    "Findings for common-noun subjects of a verb in `verbs`, skipping known actors and names capitalised mid-sentence"
    res = []
    for t in sent:
        if t.dep_ != 'nsubj' or t.pos_ != 'NOUN' or set(t.text) == {'X'} or t.lemma_.lower() in _actors: continue
        if t.head.pos_ != 'VERB' or t.head.lemma_ not in verbs or (t.i > sent.start and t.text[0].isupper()): continue
        a,b = sorted((t, t.head), key=lambda x: x.i)
        s,e = a.idx-sent.start_char, b.idx-sent.start_char+len(b.text)
        res.append(Finding(name, tell, s, e, sent.text[s:e], weight))
    return res

@rule('inert_act', tell=11, weight=2, level='sentence')
def find_inert_act(sent):
    "Subjects that cannot act, given a verb for a physical or deliberate act"
    return _inert_subj(sent, _act_verbs, 'inert_act', 11, 2)

@rule('inert_mind', tell=22, weight=SMELL, level='sentence')
def find_inert_mind(sent):
    "Subjects that cannot act, given a verb that needs a mind"
    return _inert_subj(sent, _mind_verbs, 'inert_mind', 22, SMELL)

# %% ../nbs/03_syntax.ipynb #69415f9a
def sent_rule(
    name, # Rule name, as in `core.rule`
    tell, # `write_docs` tell number
    weight, # Tier the findings carry
    pats, # Phrase list; each becomes a case-insensitive regex alternative
    anchored=False, # Match only at the sentence start?
):
    "Build and register a sentence rule that scans `pats` in the sentence text"
    pat = re.compile(('^' if anchored else '') + '(' + '|'.join(pats) + ')', re.I)
    def _f(sent): return [Finding(name, tell, m.start(), m.end(), m.group(), weight) for m in pat.finditer(sent.text)]
    _f.__name__,_f.__doc__ = f'find_{name}',f'Scan for {name} phrases'
    return rule(name, tell=tell, weight=weight, level='sentence')(_f)

find_throat = sent_rule('throat_clearing', 13, SMELL, [r"this (?:section|document|readme|page|guide|module|doc|notebook) (?:describes|covers|explains|documents|provides|outlines|introduces)", r'the purpose of this'], anchored=True)
find_todays = sent_rule('todays_world', 14, SMELL, [r"in today's"], anchored=True)
find_announce = sent_rule('announce', 15, SMELL, [r"(?:the (?:fix|answer|solution|key|result|takeaway|core \w+)|here's the thing|bottom line): "], anchored=True)
find_notxbuty = sent_rule('notxbuty', 16, KILL, [r"\bis(?:n't| not) (?:just|merely|simply|only) (?:a|an|the|about)\b", r"\baren't (?:just|merely|simply|only)\b", r"\bit's not about\b", r"\bnot (?:just|merely) about\b"])
find_teaser = sent_rule('teaser', 17, SMELL, [r"here's where it gets", r'\bthe real story\b', r'\bgets (?:really )?interesting\b', r'\bthe main event\b'])
find_appraisal = sent_rule('appraisal', 21, SMELL, [r'\bworth being precise\b', r"\bthe key (?:point|insight|thing) is\b", r"\bwhat's interesting is\b", r'\bcrucially\b', r'\bthe important thing is\b'])

@rule('rhetorical', tell=18, weight=SMELL, level='sentence')
def find_rhetorical(sent):
    "Sentences that ask the reader a question"
    t = sent.text.rstrip()
    if not t.endswith('?'): return []
    return [Finding('rhetorical', 18, 0, len(t), t, SMELL)]
